title: "Borealis Bytes"
email: contact@borealisbytes.com
timezone: America/Toronto
baseurl: "/"
permalink: "/:title/"
logo: 'assets/images/blogo.png'
favicon: 'assets/images/blogo.ico'
author: Bbadmin
paginate: 30
disqus: 'demowebsite'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: UA-113961478-1

# Authors
authors:
  shiva:
    name: Shiva
    display_name: Shiva
    avatar: 'assets/images/sal.png'
    email: shiva@borealisbytes.com
    web: https://shivasurya.me
    twitter: https://twitter.com/sshivasurya
    description: "Shiva is a senior software engineer at Borealis Bytes."
  nirooba:
    name: Nirooba
    display_name: Nirooba
    avatar: 'assets/images/niroo-1.png'
    email: nirooba@borealisbytes.com
    web: https://nirooba.com
    description: "Nirooba is a tech enthusiast and loves to code."

# Social
social:
  twitter: https://twitter.com/BytesBorealis
  github: https://github.com/borealis-bytes
  linkedin: https://www.linkedin.com/company/borealis-bytes-consulting/

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives